apiVersion: v1
kind: Service
metadata:
  name: ai-agent-service
spec:
  selector:
    app: ai-agent
  ports:
  - name: streamlit
    port: 8501
    targetPort: 8501
  - name: gradio
    port: 7860
    targetPort: 7860
  type: LoadBalancer 